apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argocd-local-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/YogeshAtigre/flaskapp/FlaskApp
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


